import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";
import PptxGenJS from "pptxgenjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.join(__dirname, "..", "..", "generated");

if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

/**
 * Parses the Reviewer agent's final text into a slide structure.
 * Understands two common shapes the Coder agent produces in "ppt" mode:
 *   1. "Slide 1: Title" headers followed by "- bullet" lines
 *   2. Markdown "# Title" / "## Title" headers followed by "- bullet" lines
 * Falls back to one slide per paragraph if neither pattern is found, so a
 * .pptx is always produced rather than failing silently.
 */
export function parseSlides(text) {
  const lines = text.split("\n").map((l) => l.trim());
  const slideHeader = /^(?:slide\s*\d+\s*[:.-]\s*|#{1,3}\s*)(.+)$/i;
  const bullet = /^[-*•]\s*(.+)$/;

  const slides = [];
  let current = null;

  for (const line of lines) {
    if (!line) continue;
    const headerMatch = line.match(slideHeader);
    const bulletMatch = line.match(bullet);

    if (headerMatch && !bulletMatch) {
      current = { title: headerMatch[1].trim(), bullets: [] };
      slides.push(current);
    } else if (bulletMatch && current) {
      current.bullets.push(bulletMatch[1].trim());
    } else if (current) {
      current.bullets.push(line);
    } else {
      current = { title: line, bullets: [] };
      slides.push(current);
    }
  }

  if (slides.length === 0) {
    slides.push({ title: "Summary", bullets: [text.slice(0, 400)] });
  }

  return slides;
}

/**
 * Renders slides to an actual .pptx file on disk and returns its filename.
 * Brand styling matches Brain's own palette (signal indigo / void background).
 */
export async function generatePptx(text, { title = "Brain Presentation" } = {}) {
  const slides = parseSlides(text);
  const pres = new PptxGenJS();

  pres.defineLayout({ name: "BRAIN_16x9", width: 10, height: 5.63 });
  pres.layout = "BRAIN_16x9";

  const titleSlide = pres.addSlide();
  titleSlide.background = { color: "0A0B0F" };
  titleSlide.addText(title, {
    x: 0.6,
    y: 2.2,
    w: 8.8,
    h: 1.2,
    fontSize: 32,
    bold: true,
    color: "E8E9ED",
    fontFace: "Georgia",
  });
  titleSlide.addText("Generated by Brain — Multi-Agent AI Platform", {
    x: 0.6,
    y: 3.3,
    w: 8.8,
    h: 0.5,
    fontSize: 12,
    color: "7C6FF0",
  });

  for (const slide of slides) {
    const s = pres.addSlide();
    s.background = { color: "0A0B0F" };
    s.addText(slide.title, {
      x: 0.5,
      y: 0.4,
      w: 9,
      h: 0.8,
      fontSize: 22,
      bold: true,
      color: "7C6FF0",
      fontFace: "Georgia",
    });
    if (slide.bullets.length) {
      s.addText(
        slide.bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
        { x: 0.6, y: 1.3, w: 8.6, h: 3.8, fontSize: 16, color: "E8E9ED", valign: "top" }
      );
    }
  }

  const filename = `brain-${Date.now()}.pptx`;
  const filepath = path.join(OUTPUT_DIR, filename);
  await pres.writeFile({ fileName: filepath });

  return { filename, url: `/files/${filename}` };
}